api = "0.2"

[buildpack]
  id = "org.cloudfoundry.icu"
  name = "ICU Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "icu"
    sha256 = "a840d1c351b90249487e3a970827a85b69632d87b723769251899881954cade0"
    source = "https://github.com/unicode-org/icu/releases/download/release-65-1/icu4c-65_1-Ubuntu18.04-x64.tgz"
    source_sha256 = "f90f422e0bc83168c97b26ba5d676ae7567e5317265a2592cb02b6d30c9c53c4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/icu/icu-65.1.0-any-stack-a840d1c3.tgz"
    version = "65.1.0"

  [[metadata.dependencies]]
    id = "icu"
    sha256 = "b31f08f61f93fd361bceeed815119cf2108d24228479abd2639ceb09a9d71b88"
    source = "https://github.com/unicode-org/icu/releases/download/release-66-1/icu4c-66_1-Ubuntu18.04-x64.tgz"
    source_sha256 = "20c995f4d1285b31cf6aace2d3e7fe12bd974e3cb6776f7a174e5976d6b88fec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/icu/icu-66.1.0-any-stack-b31f08f6.tgz"
    version = "66.1.0"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
